# This file is generated by script/update_drift_formula.rb.
class Drift < Formula
  desc "Bind markdown specs to code and check for staleness"
  homepage "https://github.com/fiberplane/drift"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.8.1/drift-aarch64-macos.tar.gz"
      sha256 "d94f199f3538515219b15d04345f121eab44bb804a70c955b013d96d59d74d60"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.8.1/drift-x86_64-macos.tar.gz"
      sha256 "ca6d93b19d4b203df5683710d2fb9e54a262764345156848259051d3d3e2ee85"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.8.1/drift-aarch64-linux.tar.gz"
      sha256 "3bf47a03d35173c9e4c2ff89de9bb9342bfee59f06f1bd1a28ea831b5f60bc7e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.8.1/drift-x86_64-linux.tar.gz"
      sha256 "48ed69e0e7180536569eb7ed7cf8910f1210f1849a032e102ba6a9e8ad9d0a91"
    end
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  def install
    bin.install "drift"
  end

  test do
    assert_match "Usage: drift <command> [options]", shell_output("#{bin}/drift --help")
  end
end
