# This file is generated by script/update_drift_formula.rb.
class Drift < Formula
  desc "Bind markdown specs to code and check for staleness"
  homepage "https://github.com/fiberplane/drift"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.1/drift-aarch64-macos.tar.gz"
      sha256 "30b68da61f8b28ea0337aeda75111692b1f2da4974c64e016f3b6a4554806c6c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.1/drift-x86_64-macos.tar.gz"
      sha256 "0845a3740404740d95e85fbec47065c3b4363f9f00e26588799c9c1c02ef9c30"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.1/drift-aarch64-linux.tar.gz"
      sha256 "02e3af09e75f398736aee179adadd8a3b8295cdd7a2d7ac8e37fc58cd4e15a35"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.1/drift-x86_64-linux.tar.gz"
      sha256 "9b13bcccc72050fd8c6290d1440e079a5a53592a18fb25d56b704a0ce69571c9"
    end
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  def install
    bin.install "drift"
  end

  test do
    assert_match "Usage: drift <command> [options]", shell_output("#{bin}/drift --help")
  end
end
