# This file is generated by script/update_drift_formula.rb.
class Drift < Formula
  desc "Bind markdown specs to code and check for staleness"
  homepage "https://github.com/fiberplane/drift"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.0/drift-aarch64-macos.tar.gz"
      sha256 "1abff42901d016df2e7b9b0072e2a5adfa0db9a870a9520d5d17cad13fe5c226"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.0/drift-x86_64-macos.tar.gz"
      sha256 "c56025a2ede4c08dbc611b8946905e5fad66dc1d0babd09424c640d416127f4d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.0/drift-aarch64-linux.tar.gz"
      sha256 "159060d7bb243316dfc8d25233691980111600554863981afafa74a95220de2e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/fiberplane/drift/releases/download/v0.9.0/drift-x86_64-linux.tar.gz"
      sha256 "fe1533c8fd475534f360c79b9316e0a1e3b66e11a5e3f21611c8eaa59809c71a"
    end
  end

  livecheck do
    url :stable
    strategy :github_latest
  end

  def install
    bin.install "drift"
  end

  test do
    assert_match "Usage: drift <command> [options]", shell_output("#{bin}/drift --help")
  end
end
