#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "net/http"
require "pathname"

OWNER = "fiberplane"
REPO = "drift"
FORMULA_PATH = Pathname(__dir__).join("..", "Formula", "drift.rb")
RELEASE_ASSETS = {
  "drift-aarch64-macos.tar.gz" => "aarch64-macos",
  "drift-x86_64-macos.tar.gz" => "x86_64-macos",
  "drift-aarch64-linux.tar.gz" => "aarch64-linux",
  "drift-x86_64-linux.tar.gz" => "x86_64-linux",
}.freeze


def github_token
  token = ENV["GITHUB_TOKEN"].to_s.strip
  token = ENV["GH_TOKEN"].to_s.strip if token.empty?
  token
end

def http_get_json(url)
  uri = URI(url)
  request = Net::HTTP::Get.new(uri)
  request["Accept"] = "application/vnd.github+json"
  request["X-GitHub-Api-Version"] = "2022-11-28"
  request["User-Agent"] = "fiberplane-homebrew-tap-updater"

  token = github_token
  request["Authorization"] = "Bearer #{token}" unless token.empty?

  response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
    http.request(request)
  end

  unless response.is_a?(Net::HTTPSuccess)
    warn "GitHub API request failed: #{response.code} #{response.message}"
    warn response.body
    exit 1
  end

  JSON.parse(response.body)
end

def http_get_text(url)
  uri = URI(url)
  request = Net::HTTP::Get.new(uri)
  request["User-Agent"] = "fiberplane-homebrew-tap-updater"

  token = github_token
  request["Authorization"] = "Bearer #{token}" unless token.empty?

  response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
    http.request(request)
  end

  case response
  when Net::HTTPSuccess
    response.body
  when Net::HTTPRedirection
    http_get_text(response.fetch("location"))
  else
    warn "Download failed: #{response.code} #{response.message}"
    warn response.body
    exit 1
  end
end

def release_for(requested_version)
  if requested_version.nil? || requested_version.empty?
    http_get_json("https://api.github.com/repos/#{OWNER}/#{REPO}/releases/latest")
  else
    tag = requested_version.start_with?("v") ? requested_version : "v#{requested_version}"
    http_get_json("https://api.github.com/repos/#{OWNER}/#{REPO}/releases/tags/#{tag}")
  end
end

def checksum_for(tag, asset)
  digest = asset["digest"].to_s
  return digest.delete_prefix("sha256:") if digest.start_with?("sha256:")

  checksum_url = "https://github.com/#{OWNER}/#{REPO}/releases/download/#{tag}/#{asset.fetch("name")}.sha256"
  http_get_text(checksum_url).split.first
end

requested_version = ARGV.first.to_s.strip
release = release_for(requested_version)
tag = release.fetch("tag_name")
version = tag.delete_prefix("v")
assets = release.fetch("assets")
assets_by_name = assets.to_h { |asset| [asset.fetch("name"), asset] }

missing_assets = RELEASE_ASSETS.keys.reject { |name| assets_by_name.key?(name) }
unless missing_assets.empty?
  warn "Release #{tag} is missing assets: #{missing_assets.join(", ")}"
  exit 1
end

checksums = RELEASE_ASSETS.keys.to_h do |name|
  [name, checksum_for(tag, assets_by_name.fetch(name))]
end

formula = <<~RUBY
  # This file is generated by script/update_drift_formula.rb.
  class Drift < Formula
    desc "Bind markdown specs to code and check for staleness"
    homepage "https://github.com/fiberplane/drift"

    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/fiberplane/drift/releases/download/#{tag}/drift-aarch64-macos.tar.gz"
        sha256 "#{checksums.fetch("drift-aarch64-macos.tar.gz")}"
      end
      if Hardware::CPU.intel?
        url "https://github.com/fiberplane/drift/releases/download/#{tag}/drift-x86_64-macos.tar.gz"
        sha256 "#{checksums.fetch("drift-x86_64-macos.tar.gz")}"
      end
    end

    on_linux do
      if Hardware::CPU.arm?
        url "https://github.com/fiberplane/drift/releases/download/#{tag}/drift-aarch64-linux.tar.gz"
        sha256 "#{checksums.fetch("drift-aarch64-linux.tar.gz")}"
      end
      if Hardware::CPU.intel?
        url "https://github.com/fiberplane/drift/releases/download/#{tag}/drift-x86_64-linux.tar.gz"
        sha256 "#{checksums.fetch("drift-x86_64-linux.tar.gz")}"
      end
    end

    livecheck do
      url :stable
      strategy :github_latest
    end

    def install
      bin.install "drift"
    end

    test do
      assert_match "Usage: drift <command> [options]", shell_output("\#{bin}/drift --help")
    end
  end
RUBY

FORMULA_PATH.write(formula)
puts "Updated #{FORMULA_PATH} to #{tag}"
